# Generated by Django 6.0.2 on 2026-03-01 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_securityevent_geo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='risk_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wafrule',
            name='rule_type',
            field=models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('lfi', 'Local File Inclusion'), ('rfi', 'Remote File Inclusion'), ('command_injection', 'Command Injection'), ('rate_limit', 'Rate Limiting'), ('geo_block', 'Geo Blocking'), ('ip_block', 'IP Block'), ('custom', 'Custom Rule')], max_length=30),
        ),
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('server', 'Servidor'), ('workstation', 'Estación de trabajo'), ('app', 'Aplicación'), ('database', 'Base de datos'), ('network', 'Equipo de red'), ('cloud', 'Servicio cloud'), ('mobile', 'Dispositivo móvil'), ('other', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('criticality', models.CharField(choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cybersecurity', 'Ciberseguridad'), ('operational', 'Operacional'), ('compliance', 'Cumplimiento normativo'), ('data', 'Datos e información'), ('infrastructure', 'Infraestructura'), ('third_party', 'Terceros / Proveedores'), ('people', 'Personas'), ('financial', 'Financiero')], max_length=20)),
                ('likelihood', models.IntegerField(choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.IntegerField(choices=[(1, 'Insignificante'), (2, 'Menor'), (3, 'Moderado'), (4, 'Mayor'), (5, 'Catastrófico')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_treatment', 'En tratamiento'), ('mitigated', 'Mitigado'), ('accepted', 'Aceptado'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('treatment_type', models.CharField(blank=True, choices=[('mitigate', 'Mitigar'), ('transfer', 'Transferir'), ('accept', 'Aceptar'), ('avoid', 'Evitar')], max_length=20)),
                ('treatment_plan', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('residual_likelihood', models.IntegerField(blank=True, choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy alta')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_impact', models.IntegerField(blank=True, choices=[(1, 'Insignificante'), (2, 'Menor'), (3, 'Moderado'), (4, 'Mayor'), (5, 'Catastrófico')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='core.itasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.organization')),
            ],
            options={
                'ordering': ['-likelihood', '-impact'],
            },
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('status_before', models.CharField(max_length=20)),
                ('status_after', models.CharField(max_length=20)),
                ('likelihood_before', models.IntegerField()),
                ('impact_before', models.IntegerField()),
                ('likelihood_after', models.IntegerField()),
                ('impact_after', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.risk')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cve_id', models.CharField(blank=True, max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('info', 'Informativa')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En progreso'), ('resolved', 'Resuelta'), ('false_positive', 'Falso positivo')], default='open', max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('remediation_notes', models.TextField(blank=True)),
                ('discovery_date', models.DateField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='core.itasset')),
                ('linked_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='core.risk')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='core.organization')),
            ],
            options={
                'ordering': ['-discovery_date'],
            },
        ),
    ]
