# Generated by Django 5.2.7 on 2025-10-08 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('individual', 'Individual'), ('summary', 'Resumen'), ('detailed', 'Detallado')], max_length=20)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF')], default='html', max_length=10)),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_results', models.ManyToManyField(related_name='reports', to='scan.scanresult')),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
    ]
