"""
Flow Labeler
============
Takes CICFlowMeter output CSVs (generated by pcap_to_csv.py) and injects
the LABEL column from the sessions.json time-window log.

Labeling strategy:
  - Each CSV row has a Timestamp column.
  - A session defines [start_ts, stop_ts] + canonical_label.
  - Any flow whose timestamp falls inside a session window gets that label.
  - Flows outside all attack windows → BENIGN.

Call:
    python -c "from lab_toolkit.label import label_all; label_all()"

Or from setup_lab.py:
    python setup_lab.py label
"""
import os, json
import pandas as pd
from pathlib import Path
from lab_toolkit.capture import _load_sessions, PCAP_DIR

# CICFlowMeter output directory (pcap_to_csv.py puts files here)
FLOW_CSV_DIR  = Path("media/training/datasets/jorise_lab")
LABELED_DIR   = FLOW_CSV_DIR  # overwrite in-place (backup kept)

TIMESTAMP_COL = "Timestamp"        # CICFlowMeter default
LABEL_COL     = "Label"


def _parse_ts(val) -> float:
    """Parse CICFlowMeter timestamp to Unix float."""
    import datetime
    if isinstance(val, float):
        return val
    # CICFlowMeter format: "12/07/2023 18:42:37"
    try:
        return float(val)
    except (ValueError, TypeError):
        pass
    for fmt in ["%d/%m/%Y %H:%M:%S", "%Y-%m-%d %H:%M:%S", "%m/%d/%Y %H:%M:%S"]:
        try:
            return datetime.datetime.strptime(str(val), fmt).timestamp()
        except ValueError:
            continue
    return float('nan')


def label_csv(csv_path: str, sessions: list) -> pd.DataFrame:
    """Label one CICFlowMeter CSV using session time windows."""
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    if TIMESTAMP_COL not in df.columns:
        # CICFlowMeter may use 'Timestamp' or 'timestamp'
        ts_col = next((c for c in df.columns if 'timestamp' in c.lower()), None)
        if ts_col:
            df = df.rename(columns={ts_col: TIMESTAMP_COL})
        else:
            print(f"  [label] WARNING: No timestamp column in {csv_path} — all rows → BENIGN")
            df[LABEL_COL] = "BENIGN"
            return df

    df["_ts_unix"] = df[TIMESTAMP_COL].apply(_parse_ts)
    df[LABEL_COL] = "BENIGN"

    for s in sessions:
        if s["stop_ts"] is None:
            continue  # session still open, skip
        mask = (df["_ts_unix"] >= s["start_ts"]) & (df["_ts_unix"] <= s["stop_ts"])
        df.loc[mask, LABEL_COL] = s["canonical_label"]

    n_attack = (df[LABEL_COL] != "BENIGN").sum()
    n_benign = (df[LABEL_COL] == "BENIGN").sum()
    print(f"  [label] {os.path.basename(csv_path)}  →  "
          f"{n_attack} attack rows, {n_benign} benign rows")

    df = df.drop(columns=["_ts_unix"])
    return df


def label_all(flow_dir: str | None = None):
    """Label all unlabeled CSVs in the flow CSV directory."""
    flow_dir = Path(flow_dir) if flow_dir else FLOW_CSV_DIR
    sessions = _load_sessions()

    if not sessions:
        print("[label] No sessions found in sessions.json. "
              "Run capture sessions first.")
        return

    csv_files = list(flow_dir.glob("*.csv"))
    if not csv_files:
        print(f"[label] No CSV files found in {flow_dir}")
        return

    print(f"[label] Labeling {len(csv_files)} CSV files using {len(sessions)} sessions...")
    flow_dir.mkdir(parents=True, exist_ok=True)

    for f in csv_files:
        df = label_csv(str(f), sessions)
        backup = str(f).replace(".csv", ".unlabeled.csv")
        if not os.path.exists(backup):
            import shutil; shutil.copy(f, backup)
        df.to_csv(str(f), index=False)

    print(f"[label] Done. Labeled files in {flow_dir}")
    print(f"[label] Original files backed up as *.unlabeled.csv")


def label_distribution(flow_dir: str | None = None) -> dict:
    """Print label distribution across all labeled CSVs."""
    from collections import Counter
    flow_dir = Path(flow_dir) if flow_dir else FLOW_CSV_DIR
    counts: Counter = Counter()
    for f in flow_dir.glob("*.csv"):
        if ".unlabeled" in f.name:
            continue
        df = pd.read_csv(f, usecols=lambda c: c.strip() == LABEL_COL)
        df.columns = df.columns.str.strip()
        if LABEL_COL in df.columns:
            counts.update(df[LABEL_COL].value_counts().to_dict())
    print("\nLabel Distribution — Jorise Lab Dataset")
    print("-" * 40)
    for label, n in counts.most_common():
        print(f"  {label:<25} {n:>8,}")
    return dict(counts)
