# Generated by Django 6.0.2 on 2026-03-01 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('algorithm', models.CharField(choices=[('xgboost', 'XGBoost Multiclass'), ('random_forest', 'Random Forest Multiclass')], max_length=30)),
                ('status', models.CharField(choices=[('training', 'Training'), ('evaluating', 'Evaluating'), ('active', 'Active'), ('retired', 'Retired'), ('failed', 'Failed')], default='training', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('n_splits', models.IntegerField(default=5)),
                ('sample_per_file', models.IntegerField(default=15000)),
                ('n_samples_total', models.IntegerField(default=0)),
                ('n_features', models.IntegerField(default=0)),
                ('classes', models.JSONField(default=list)),
                ('feature_names', models.JSONField(default=list)),
                ('cv_accuracy', models.FloatField(blank=True, null=True)),
                ('cv_macro_f1', models.FloatField(blank=True, null=True)),
                ('cv_macro_precision', models.FloatField(blank=True, null=True)),
                ('cv_macro_recall', models.FloatField(blank=True, null=True)),
                ('cv_std_f1', models.FloatField(blank=True, null=True)),
                ('cv_per_class_json', models.JSONField(blank=True, default=dict)),
                ('cv_fold_metrics', models.JSONField(blank=True, default=list)),
                ('feature_importances', models.JSONField(blank=True, default=dict)),
                ('dominant_features', models.JSONField(blank=True, default=list)),
                ('top10_features', models.JSONField(blank=True, default=list)),
                ('passes_targets', models.BooleanField(blank=True, null=True)),
                ('weak_classes', models.JSONField(blank=True, default=list)),
                ('cross_domain_avg_f1', models.FloatField(blank=True, null=True)),
                ('cross_domain_pass_rate', models.FloatField(blank=True, null=True)),
                ('cross_domain_verdict', models.CharField(blank=True, max_length=30)),
                ('cross_domain_detail', models.JSONField(blank=True, default=dict)),
                ('anomaly_fpr', models.FloatField(blank=True, null=True)),
                ('anomaly_dr', models.FloatField(blank=True, null=True)),
                ('anomaly_f1', models.FloatField(blank=True, null=True)),
                ('ensemble_w_clf', models.FloatField(default=0.6)),
                ('ensemble_w_anomaly', models.FloatField(default=0.4)),
                ('ensemble_w_context', models.FloatField(default=0.0)),
                ('model_file', models.CharField(blank=True, max_length=500)),
                ('scaler_file', models.CharField(blank=True, max_length=500)),
                ('le_file', models.CharField(blank=True, max_length=500)),
                ('anomaly_file', models.CharField(blank=True, max_length=500)),
                ('ensemble_file', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('error_msg', models.TextField(blank=True)),
                ('training_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_unified_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_version_str', models.CharField(blank=True, max_length=20)),
                ('feature_hash', models.CharField(db_index=True, max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('flow_duration_ms', models.FloatField(blank=True, null=True)),
                ('ensemble_score', models.FloatField()),
                ('clf_prob_attack', models.FloatField(null=True)),
                ('anomaly_score', models.FloatField(null=True)),
                ('predicted_class', models.CharField(max_length=50)),
                ('is_threat', models.BooleanField()),
                ('confidence', models.CharField(blank=True, max_length=10)),
                ('top_features_json', models.JSONField(blank=True, default=list)),
                ('explanation_text', models.TextField(blank=True)),
                ('analyst_verdict', models.CharField(blank=True, max_length=20)),
                ('analyst_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_predictions', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='training.unifiedmodelversion')),
            ],
            options={
                'db_table': 'training_prediction_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'is_threat'], name='training_pr_timesta_6f3536_idx'), models.Index(fields=['predicted_class'], name='training_pr_predict_50c27b_idx'), models.Index(fields=['analyst_verdict'], name='training_pr_analyst_5b29db_idx')],
            },
        ),
    ]
